main: de.timesnake.game.survival.main.GameSurvival
version: 1.2.0
name: game-survival
author: timesnake
depend: [ basic-bukkit ]
api-version: 1.13

commands:
  private:
    aliases: [ pv ]
  back:
  survivalspawn:
  spawnsurvival:
  sspawn:
  stash:
  tprandom:
  tprand:
  randomtp: