main: de.timesnake.game.survival.main.GameSurvival
version: ${version}
name: game-survival
author: timesnake
depend: [ basic-bukkit ]
api-version: 1.21

commands:
  private:
    aliases: [ pv ]
  survivalspawn:
  spawnsurvival:
  sspawn:
  messi:
  tprandom:
  tprand:
  randomtp: